name: CI

on:
  push:
    branches:
    tags:
  workflow_dispatch:

jobs:
  build-test:
    env:
      EXCLUDED_BUILD_TARGETS: -zetasql/jdk/... -java/... -javatests/...
      MACOS_BUILD_ARGS: --features=-supports_dynamic_linker --config=clang --copt "-O3"
      BAZEL_LINUX_CACHE: --remote_cache=https://storage.googleapis.com/snowsql-bazel-linux-cache --google_credentials=service_account_credentials.json
      BAZEL_MACOS_CACHE: --remote_cache=https://storage.googleapis.com/snowsql-bazel-macos-cache --google_credentials=service_account_credentials.json

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build-command: bazel build ${BAZEL_LINUX_CACHE} -- //... ${EXCLUDED_BUILD_TARGETS}
            lib-path: bazel-bin/zetasql/local_service/libremote_server.so
            test-command: bazel test ${BAZEL_LINUX_CACHE} -- //... ${EXCLUDED_BUILD_TARGETS}

          - os: macos-latest
            build-command: |
              bazel build -- //... ${MACOS_BUILD_ARGS} ${BAZEL_MACOS_CACHE} ${EXCLUDED_BUILD_TARGETS}
              install_name_tool -id "@loader_path/libremote_server.dylib" bazel-bin/zetasql/local_service/libremote_server.dylib
            lib-path: bazel-bin/zetasql/local_service/libremote_server.dylib
            test-command: bazel test ${MACOS_BUILD_ARGS} ${BAZEL_MACOS_CACHE} -- //... ${EXCLUDED_BUILD_TARGETS}

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.1.0

      - name: Prepare Google service account credentials
        run: echo "$GCS_SERVICE_ACCOUNT" > service_account_credentials.json
        env:
          GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}

      - name: Bazel build
        run: ${{ matrix.build-command }}

      - name: Bazel test
        run: ${{ matrix.test-command }}

      - name: Archive build artifacts
        run: tar -cvzf ${{ matrix.lib-path }}.tar.gz ${{ matrix.lib-path }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}
          path: ${{ matrix.lib-path }}.tar.gz
