name: CI

on:
  push:
    branches:
    tags:
  workflow_dispatch:

jobs:
  build-test:
    env:
      BAZEL_LINUX_CACHE_ARGS: --remote_cache=https://storage.googleapis.com/snowsql-bazel-linux-cache --google_credentials=service_account_credentials.json
      BAZEL_MACOS_CACHE_ARGS: --remote_cache=https://storage.googleapis.com/snowsql-bazel-macos-cache --google_credentials=service_account_credentials.json

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            build-command: bazel build ${BAZEL_LINUX_CACHE_ARGS} -- //zetasql/local_service:libremote_server.so -zetasql/jdk/... -java/... -javatests/...
            test-command: |
              bazel test ${BAZEL_LINUX_CACHE_ARGS} -- //... -zetasql/jdk/... -java/... -javatests/... -zetasql/local_service:libremote_server.dylib \
                -zetasql/reference_impl:algebrizer_test \
                -zetasql/resolved_ast:resolved_ast_deep_copy_visitor_test \
                -zetasql/reference_impl:reference_compliance_test_minimal_rewrites \
                -zetasql/reference_impl:reference_compliance_test \
                -zetasql/reference_impl:reference_compliance_test_all_rewrites
            lib-path: bazel-bin/zetasql/local_service/libremote_server.so

          - os: macos-latest
            build-command: |
              bazel build --features=-supports_dynamic_linker --config=clang --copt "-O3" ${BAZEL_MACOS_CACHE_ARGS} -- //zetasql/local_service:libremote_server.dylib -zetasql/jdk/... -java/... -javatests/...
              install_name_tool -id "@loader_path/libremote_server.dylib" bazel-bin/zetasql/local_service/libremote_server.dylib
            test-command: |
              bazel test --features=-supports_dynamic_linker --config=clang --copt "-O3" ${BAZEL_MACOS_CACHE_ARGS} -- //... -zetasql/jdk/... -java/... -javatests/... -zetasql/local_service:libremote_server.so \
                -zetasql/analyzer:analyzer_set_operation_test \
                -zetasql/common:multiprecision_int_test \
                -zetasql/public:proto_value_conversion_test \
                -zetasql/public/functions:math_test \
                -zetasql/reference_impl:algebrizer_test \
                -zetasql/resolved_ast:resolved_ast_deep_copy_visitor_test \
                -zetasql/tools/execute_query:execute_query_tool_test \
                -zetasql/reference_impl:reference_compliance_test \
                -zetasql/reference_impl:reference_compliance_test_minimal_rewrites
                -zetasql/reference_impl:reference_compliance_test_all_rewrites
            lib-path: bazel-bin/zetasql/local_service/libremote_server.dylib

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.1.0

      - name: Prepare Google service account credentials
        run: echo "$GCS_SERVICE_ACCOUNT" > service_account_credentials.json
        env:
          GCS_SERVICE_ACCOUNT: ${{ secrets.GCS_SERVICE_ACCOUNT }}

      - name: Bazel build
        run: ${{ matrix.build-command }}

      - name: Bazel test
        run: ${{ matrix.test-command }}

      - name: Archive build artifacts
        run: tar -cvzf ${{ matrix.lib-path }}.tar.gz ${{ matrix.lib-path }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}
          path: ${{ matrix.lib-path }}.tar.gz
