name: run_tests

on:
  push:
    branches:
    tags:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cache-path: ~/.cache/bazel
            build-command: bazel build //zetasql/local_service:libremote_server.so
            test-command: |
              bazel test //zetasql/analyzer/...
              bazel test //zetasql/base/...
              bazel test //zetasql/common/...
              bazel test //zetasql/compliance/...
              bazel test //zetasql/local_service/...
              bazel test //zetasql/parser/...

          - os: macos-latest
            cache-path: /private/var/tmp
            build-command: bazel build //zetasql/local_service:libremote_server.dylib --features=-supports_dynamic_linker
            test-command: |
              bazel test //zetasql/analyzer/... --features=-supports_dynamic_linker
              bazel test //zetasql/base/... --features=-supports_dynamic_linker
              bazel test //zetasql/common/... --features=-supports_dynamic_linker
              bazel test //zetasql/compliance/... --features=-supports_dynamic_linker
              bazel test //zetasql/local_service/... --features=-supports_dynamic_linker
              bazel test //zetasql/parser/... --features=-supports_dynamic_linker

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: set environment variable with bazel version
        run: echo "BAZEL_VERSION=$(cat .bazelversion)" >> $GITHUB_ENV

      - name: Setup bazelisk
        uses: bazelbuild/setup-bazelisk@v2
    
      - name: Mount bazel cache
        uses: actions/cache@v3
        with:
          path: "${{ matrix.cache-path }}"
          key: ${{ runner.os }}-${{ env.BAZEL_VERSION }}-bazel

      - name: Bazel build
        run: ${{ matrix.build-command }}

      - name: Run bazel tests
        run: ${{ matrix.test-command }}
